---
title: "Manuscript figures"
output: html_document
date: "2024-01-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(arrow)
library(lubridate)
library(tidytext)
library(ggpattern)
library(ggpubr)
library(ggh4x)
```

## Read in the data and model metadata
```{r read-in-data}
lake_sites <- c('TOOK', 'PRLA','PRPO', 'CRAM', 'LIRO','BARC', 'SUGG')

# read in the metadata from the google sheet
googlesheets4::gs4_deauth()
model_meta <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1oC7_w63wSCXNiHs1IK8AFGr0MG-NdjDAjwkfjvRZW-I/edit?usp=sharing")

baselines <- model_meta |> 
  filter(model_id %in% c('persistenceRW', 'climatology'))
# Open dataset-------------
# start with lake temperatures
temperature_scores <- arrow::open_dataset("./scores_2023") |>
  dplyr::filter(!(model_id %in% c('flareGOTM','flareGOTM_noDA', 'flare_ler', 'flare_ler_baseline') &
                  site_id == 'TOOK')) |> 
  filter(site_id %in% lake_sites,
         model_id %in% model_meta$model_id,
         variable == 'temperature') |>
  collect()


# Calculate skill scores ------------
temperature_climatology <- arrow::open_dataset("./scores_2023") |>
  filter(model_id == 'climatology', 
         site_id %in% lake_sites,
         variable == 'temperature') |>
  collect() |> 
  select(reference_datetime, datetime, crps, logs, site_id, model_id) |> 
  arrange(reference_datetime, datetime, site_id) |> 
  pivot_wider(values_from = c(crps, logs),
              names_from = model_id)

temperature_skill <- temperature_scores |>
  filter(model_id != 'climatology') |> 
  select(reference_datetime, datetime, crps, logs, site_id, model_id) |> 
  full_join(temperature_climatology) |> 
  
  # calcaulte the skill relative to climatology (- is bad, + is good)
  mutate(skill_crps = crps_climatology - crps,
         skill_logs = logs_climatology - logs,
         horizon = as.numeric(as_date(datetime) - as_date(reference_datetime))) |> 
  # consistent forecast period
  filter(horizon <= 30,
         horizon >= 1, 
         horizon != 15) |> 
  arrange(reference_datetime, site_id, datetime, model_id) 

source('R/get_colours.R') # returns model_id_colours and cols_modeltypes

```


## Figure 1

```{r model-type, fig.width=10}
top10_temp <- 
  temperature_skill |> 
  group_by(model_id) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  ungroup() |>
  filter(mean_crps > 0) |>
  left_join(model_meta) |> 
  mutate(manuscript_name = fct_reorder(manuscript_name, mean_crps),
         uses_NOAA = ifelse(uses_NOAA == 1, 'yes', 'no'), 
         uses_AT = str_detect(NOAA_var, 'air_temperature')) |> 
  ggplot(aes(x=mean_crps, y = manuscript_name, fill = model_type)) +    # Different pattern for each group
  geom_bar_pattern(aes(pattern = as.factor(uses_AT)),
                   stat = "identity",
                   alpha = 0.8, 
                   pattern_fill = "black",
                   pattern_colour = "black", 
                   pattern_spacing = 0.04,
                   pattern_alpha = 1,
                   colour = 'black') + 
  scale_y_reordered() +
  labs(y='Model', x = 'mean relative skill (°C)') +
  geom_vline(xintercept = 0) +
  scale_fill_manual(values = cols_modeltype) +
  scale_pattern_manual(values=c('none', 'stripe')) +
  scale_pattern_type_manual(values=c(NA, NA)) +
  theme_bw() + 
  guides(pattern = guide_legend(override.aes = list(fill = "white", pattern_spacing = 0.02), 
                                title = 'Uses air temperature as a covariate?'),
         fill = guide_legend(override.aes = list(pattern = "none"), title = 'Model class'))

all_temp <- 
  temperature_skill |> 
  group_by(model_id) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  left_join(model_meta) |> 
  mutate(manuscript_name = fct_reorder(manuscript_name, mean_crps),
         uses_NOAA = ifelse(uses_NOAA == 1, 'yes', 'no'), 
         uses_AT = str_detect(NOAA_var, 'air_temperature')) |> 
  ggplot(aes(x=mean_crps, y = manuscript_name, fill = model_type)) +    # Different pattern for each group

  geom_bar_pattern(aes(pattern = as.factor(uses_AT)),
                   stat = "identity",
                   alpha = 0.8, 
                   colour = 'black',
                   pattern_fill = "black",
                   pattern_colour = "black", width = 0.8,
                   pattern_spacing = 0.03,
                   pattern_alpha = 1) + 
  scale_y_reordered() +
  labs(y='Model', x = 'mean relative skill (°C)') +
  geom_vline(xintercept = 0) +
  scale_fill_manual(values = cols_modeltype) +
  scale_pattern_manual(values=c('none', 'stripe'), name = 'Uses air temperature as a covariate?') +
  scale_pattern_type_manual(values=c(NA, NA), name = 'Uses air temperature as a covariate?') +
  theme_bw() + 
  guides(pattern = guide_legend(override.aes = list(fill = "white"), title = 'Uses air temperature as a covariate?'),
         fill = guide_legend(override.aes = list(pattern = "none"), title = 'Model class'))

ggpubr::ggarrange(top10_temp, all_temp, nrow = 1, align = 'hv',
                  common.legend = T,
                  legend = 'top', labels = 'auto') |> 
  ggsave(filename = './Plots/Figure1.png', width = 25, height = 10, units = 'cm')

```

## Figure 2
```{r skill-bias-sd}
skill <- 
  temperature_skill |> 
  filter(model_id %in% c(top_mods$model_id) & model_id != 'persistenceRW', 
         horizon > 0, 
         horizon != 15,
         horizon <=30) |> 
  group_by(model_id, horizon) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  left_join(select(model_meta, model_id, manuscript_name)) |> 
  mutate(manuscript_name = factor(manuscript_name, levels = levels(model_id_colours$manuscript_name))) |> 
  ggplot(aes(x=horizon, 
             y = mean_crps, colour = manuscript_name)) +
  geom_hline(yintercept = 0, colour = 'grey40' ) + 
  geom_line()  +  
  labs(y='mean relative skill (°C)', x = 'Horizon (days)') +
  scale_colour_manual(name = 'Model',values = model_id_colours$value) +
  theme_bw()

 

sd <- temperature_scores |> 
  mutate(horizon = as_date(datetime) - as_date(reference_datetime)) |> 
  filter(model_id %in% top_mods$model_id & model_id != 'persistenceRW',  
         horizon > 0, 
         horizon != 15,
         horizon <=30) |>
  group_by(model_id, horizon) |> 
  summarise(mean_sd = mean(sd, na.rm = T)) |> 
  left_join(select(model_meta, model_id, manuscript_name)) |> 
  mutate(manuscript_name = factor(manuscript_name, levels = levels(model_id_colours$manuscript_name))) |> 
  ggplot(aes(x=horizon, 
             y = mean_sd, colour = manuscript_name)) +
  geom_line()+
  labs(y='mean standard deviation (°C)', x = 'Horizon (days)') +
  scale_colour_manual(name = 'Model',values = model_id_colours$value) +
  theme_bw()

bias <- temperature_scores |> 
  mutate(horizon = as_date(datetime) - as_date(reference_datetime),
         abs_bias = abs(mean - observation)) |> 
  filter(model_id %in% top_mods$model_id & model_id != 'persistenceRW', 
         horizon > 0, 
         horizon != 15,
         horizon <= 30) |>
  group_by(model_id, horizon) |> 
  summarise(mean_abs_bias = mean(abs_bias, na.rm = T)) |> 
  left_join(select(model_meta, model_id, manuscript_name)) |> 
  mutate(manuscript_name = factor(manuscript_name, levels = levels(model_id_colours$manuscript_name))) |> 
  ggplot(aes(x=horizon, 
             y = mean_abs_bias, colour = manuscript_name)) +
  geom_line()+
  labs(y='mean absolute bias (°C)', x = 'Horizon (days)') +
  scale_colour_manual(name = 'Model',values = model_id_colours$value) +
  theme_bw() +
  coord_cartesian(ylim = c(0, 2))

ggpubr::ggarrange(skill, 
                  ggarrange(as_ggplot(get_legend(bias)), NULL, widths = c(0.5, 1.5)),  
                  sd, 
                  bias, 
                  legend = F, align = 'hv', 
                  labels = c('a','', 'b', 'c')) |> 
  ggsave(filename = 'Plots/Figure2.png', height = 17, width = 16, units = 'cm')
```

## Figure 3

```{r reliability}
source('./R/reliability_plot.R')

good_80 <- 
  plot_reliability(scores = temperature_scores,
                   models = top_mods, # model_ids and manuscript names
                   CI = 80, 
                   order = levels(model_id_colours$manuscript_name)) +
  scale_colour_manual(name = 'Model',values = model_id_colours$value) +
  theme_bw() +
  scale_y_continuous(limits = c(45, 100))

good_95 <- plot_reliability(scores = temperature_scores,
                            models = top_mods, 
                            CI = 95, 
                            order = levels(model_id_colours$manuscript_name)) +
  scale_colour_manual(name = 'Model',values = model_id_colours$value) +
  theme_bw() +
  scale_y_continuous(limits = c(45, 100))

# get the list of bad models
bad_mods <- model_meta |> 
  filter(!model_id %in% top_mods$model_id) |> 
  select(model_id, manuscript_name)

bad_80 <- 
  plot_reliability(scores = temperature_scores,
                 models = bad_mods, 
                 CI = 80, 
                 order = bad_mods$manuscript_name) +
    theme_bw() +
    scale_colour_manual(name = '', values = rep('grey50', 20)) +
    scale_y_continuous(limits = c(0, 100)) + 
    theme(legend.position = 'none')

bad_95 <- plot_reliability(scores = temperature_scores,
                            models = bad_mods, 
                            CI = 95, 
                            order = bad_mods$manuscript_name) +
  theme_bw() +
  scale_y_continuous(limits = c(0, 100))  +
  scale_colour_manual(name = '', values = rep('grey50', 20))


ggarrange(ggarrange(get_legend(good_80), NULL, nrow = 2),
          ggarrange(good_80, good_95, bad_80, bad_95, align = 'hv', legend= 'none', labels = 'auto'), 
          ncol = 2, 
          widths = c(1,5)) |> 
  ggsave(filename = 'Plots/Figure3.png', height = 17.6, width = 23, units = 'cm')
```

## Figure 4
```{r model_type-site}
n_model_type <- temperature_skill |> 
  distinct(model_id) |> 
  left_join(model_meta) |>
  group_by(model_type) |> 
  summarise(n = n())  |> 
  mutate(site_id = 'TOOK', mean_skill = -3.25) |> 
  filter(model_type != 'null')


# top 10 average models
top_mods <- temperature_skill |> 
  group_by(model_id) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  ungroup() |> 
  filter(mean_crps > 0) |> 
  distinct(model_id)


A <- temperature_skill |> 
  left_join(model_meta, by = 'model_id') |>
  filter(model_type != 'null') |> 
  group_by(model_type, model_id, site_id) |> 
  summarise(mean_skill = mean(skill_crps, na.rm = T)) |>  
  ggplot(aes(x = mean_skill, 
             y = site_id, 
             colour = model_type)) +
  geom_vline(xintercept = 0, linetype = 'solid') +
  geom_text(data = n_model_type, aes(label = paste0('n = ', n)))+ 
  geom_boxplot() +
  facet_wrap(~model_type, scales = 'free_y',nrow = 2) +
  labs(y='Site', x = 'mean relative skill (°C)') +
  scale_colour_manual(values = cols_modeltype, name = 'Model class') +
  theme_bw() 
  
B <- temperature_skill |> 
  filter(model_id %in% top_mods$model_id) |> 
  group_by(site_id, horizon) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  mutate(site_id = factor(site_id, levels = lake_sites)) |> 
  ggplot(aes(x=horizon, 
             y = mean_crps, colour = site_id)) +
  geom_hline(yintercept = 0, colour = 'grey40') + 
  geom_line()  +  
  labs(y='mean relative skill (°C)', x = 'Horizon (days)') +
  scale_colour_brewer(palette = 'Dark2', name = 'Site')+
  theme_bw()

cowplot::plot_grid(A, B, nrow = 2, rel_heights = c(1.5, 1), align = 'v', axis = 'lr', labels = 'auto') |> 
  ggsave(filename = './Plots/Figure4.png', width = 19, height = 16, units = 'cm')
```

## Figure 5

```{r target-plot}
targets <- readr::read_csv("https://data.ecoforecast.org/neon4cast-targets/aquatics/aquatics-targets.csv.gz") |> 
  na.omit()

layout_design <- "
  A#
  BC
  DE
  FG
"

# is 2023 a stand out year?
targets_2023 <- targets |> 
  filter(variable == 'temperature',
         site_id %in% lake_sites, 
         year(datetime) == 2023) |> 
  mutate(month = as.factor(month(datetime))) |> 
  group_by(month, site_id) |> 
  summarise(mean_obs = mean(observation, na.rm = T),
            n = n()) |> 
  mutate(mean_obs = ifelse(n < 18, NA, mean_obs))


obs <- targets |> 
  filter(variable == 'temperature',
         site_id %in% lake_sites,
         year(datetime) < 2023) |> 
  mutate(month = as.factor(month(datetime))) |> 
  ggplot(aes(x = month, y= observation), colour = "#26172AFF") +
  geom_boxplot() +
  facet_manual(~factor(site_id, levels = lake_sites),
               design = layout_design) +
  geom_point(data = targets_2023, aes(x = month, y = mean_obs), colour = '#60CEACFF') +
  scale_x_discrete(name = 'Month', labels = month.abb) +
  scale_y_continuous(name = 'Water temperature (°C)') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))

ggsave(obs, filename = 'Plots/Figure5.png', width = 10, height=13, units = 'cm')

```


```{r}
targets |> 
  filter(variable == 'temperature',
         site_id %in% lake_sites, 
         year(datetime) < 2024) |> 
  mutate(doy = yday(datetime),
         year = year(datetime),
         site_id = factor(site_id, levels = lake_sites), 
         is_2023 = ifelse(year == 2023, T, F))  |> 
  group_by(site_id, is_2023) |> 
  summarise(mean = mean(observation),
            sd = sd(observation)) |> 
  filter(site_id  == 'BARC')
```
 
 