---
title: "Manuscript figures"
output: html_document
date: "2024-01-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(arrow)
library(lubridate)
library(tidytext)
library(ggpattern)
library(ggpubr)
library(ggh4x)
# source('install_packages.R')
```

## Get scores

```{r}
if (!dir.exists('scores')) {
  source('R/get_scores.R')
}
```

## Read in the data and model metadata
```{r read-in-data}
lake_sites <- c('TOOK', 'PRLA','PRPO', 'CRAM', 'LIRO','BARC', 'SUGG')

# read in the metadata from the google sheet
model_meta <- read_csv("https://zenodo.org/records/11087208/files/Model_descriptions.csv?download=1", na = 'character')

baselines <- model_meta |> 
  filter(model_id %in% c('persistenceRW', 'climatology'))
source('R/load_data.R')

source('R/get_colours.R') # returns model_id_colours and cols_modeltypes

if (!dir.exists('Plots')) {
  dir.create('Plots')
}
```

## Inventory

```{r}

# How many models?
model_meta |>
  mutate(tw = str_detect(variable, 'temperature'),
         do = str_detect(variable, 'oxygen')) |> 
  summarise(sum(tw), sum(do))

model_meta |> 
  group_by(variable) |> 
  summarise(n())


# model classes by variable
model_meta |> 
  filter(str_detect(variable, 'temperature')) |> 
  group_by(model_type) |> 
  summarise(n())

model_meta |> 
  filter(str_detect(variable, 'oxygen')) |> 
  group_by(model_type) |> 
  summarise(n())


# use AT as a covariate?
model_meta |> 
  select(model_id, NOAA_var, variable) |>
  mutate(tw = str_detect(variable, 'temperature'),
         do = str_detect(variable, 'oxygen')) |> 
  filter(str_detect(NOAA_var, 'air_temp')) |>
  summarise(sum(tw), sum(do))


# types of uncertainty represented
# Number of models that contain each type
model_meta |>
  mutate(tw = str_detect(variable, 'temperature'))  |> 
  filter(tw == T) |> 
  summarise(across(contains('unc'), ~ sum(.x, na.rm = T)))



# How many sources are represented in each model?
model_meta |>
  mutate(tw = str_detect(variable, 'temperature'))  |> 
  filter(tw == T) |> 
  select(model_id, contains('unc_')) |> 
  mutate(unc_n = rowSums(pick(where(is.numeric)))) |> 
  group_by(unc_n) |> 
  summarise(n = n())


# Scores database summary -------------------------------------------------
# total forecasts - distinct model/site/var/refdate combos
distinct_forecasts <- arrow::open_dataset("./scores") |> 
  distinct(model_id, site_id, variable, reference_datetime) |> 
  collect()

# variable forecasts
distinct_forecasts |> 
  group_by(variable ) |>
  summarise(n = n()) |> 
  mutate(percent = 100*(n/nrow(distinct_forecasts)))

```

## Figure 2

```{r model-type, fig.width=10}
top10_temp <- 
  temperature_skill |>
  group_by(model_id) |>
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |>
  ungroup() |>
  filter(mean_crps < 0) |>
  left_join(model_meta) |>
  mutate(manuscript_name = fct_reorder(manuscript_name, desc(mean_crps)),
         uses_NOAA = ifelse(uses_NOAA == 1, 'yes', 'no'),
         uses_AT = str_detect(NOAA_var, 'air_temperature')) |>
  ggplot(aes(x=mean_crps, y = manuscript_name, fill = model_type)) +    # Different pattern for each group
  geom_bar_pattern(aes(pattern = as.factor(uses_AT)),
                   stat = "identity",
                   alpha = 0.8,
                   pattern_fill = "black",
                   pattern_colour = "black",
                   pattern_spacing = 0.04,
                   pattern_alpha = 1,
                   colour = 'black') +
  scale_y_reordered() +
  labs(y='Model', x = 'Mean relative skill (°C)', subtitle = 'Water temperature') +
  geom_vline(xintercept = 0) +
  scale_fill_manual(values = cols_modeltype) +
  scale_pattern_manual(values=c('none', 'stripe')) +
  scale_pattern_type_manual(values=c(NA, NA)) +
  theme_bw(base_size = 10) +
  guides(pattern = guide_legend(override.aes = list(fill = "white", pattern_spacing = 0.02),
                                title = 'Uses air temperature\nas a covariate?'),
         fill = guide_legend(override.aes = list(pattern = "none"), title = 'Model class')) +
  theme(legend.box = 'vertical')

all_temp <- 
  temperature_skill |> 
  group_by(model_id) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  left_join(model_meta) |> 
  mutate(manuscript_name = fct_reorder(manuscript_name, desc(mean_crps)),
         uses_NOAA = ifelse(uses_NOAA == 1, 'yes', 'no'), 
         uses_AT = str_detect(NOAA_var, 'air_temperature')) |> 
  ggplot(aes(x=mean_crps, y = manuscript_name, fill = model_type)) +   # Different pattern for each group
  annotate('rect', xmax = Inf, xmin = -Inf, ymin = 19.5, ymax =  Inf, fill = 'grey', alpha = 0.2) + 
  geom_bar_pattern(aes(pattern = as.factor(uses_AT)),
                   stat = "identity",
                   alpha = 0.8, 
                   colour = 'black',
                   pattern_fill = "black",
                   pattern_colour = "black", width = 0.8,
                   pattern_spacing = 0.03,
                   pattern_alpha = 1) + 
  scale_y_reordered() +
  labs(y='Model', x = 'Mean relative skill (°C)', subtitle = 'Water temperature') +
  geom_vline(xintercept = 0) +
  scale_fill_manual(values = cols_modeltype) +
  scale_pattern_manual(values=c('none', 'stripe'), name = 'Uses air temperature as a covariate?') +
  scale_pattern_type_manual(values=c(NA, NA), name = 'Uses air temperature as a covariate?') +
  theme_bw(base_size = 10) + 
  guides(pattern = guide_legend(override.aes = list(fill = "white"), title = 'Uses air temperature as a covariate?'),
         fill = guide_legend(override.aes = list(pattern = "none"), title = 'Model class'))  +
  theme(legend.box = 'vertical')


all_DO <- oxygen_skill |> 
  group_by(model_id) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  left_join(model_meta) |> 
  mutate(manuscript_name = fct_reorder(manuscript_name, desc(mean_crps)),
         uses_NOAA = ifelse(uses_NOAA == 1, 'yes', 'no'), 
         uses_AT = str_detect(NOAA_var, 'air_temperature')) |> 
  ggplot(aes(x=mean_crps, y = manuscript_name, fill = model_type)) +    # Different pattern for each group
  annotate('rect', xmax = Inf, xmin = -Inf, ymin = 9.5, ymax =  Inf, fill = 'grey', alpha = 0.2) + 
  geom_bar_pattern(aes(pattern = as.factor(uses_AT)),
                   stat = "identity",
                   alpha = 0.8, 
                   pattern_fill = "black",
                   pattern_colour = "black", 
                   pattern_spacing = 0.04,
                   pattern_alpha = 1,
                   colour = 'black') + 
  scale_y_reordered() +
  labs(y='Model', x = 'Mean relative skill (mg/L)', subtitle = 'Dissolved oxygen') +
  geom_vline(xintercept = 0) +
  scale_fill_manual(values = cols_modeltype) +
  scale_pattern_manual(values=c('none', 'stripe')) +
  scale_pattern_type_manual(values=c(NA, NA)) +
  theme_bw(base_size = 10) + 
  theme(legend.position = 'none')


legend <- get_legend(top10_temp)
ggpubr::ggarrange(top10_temp, ggarrange(as_ggplot(legend), NULL, ncol = 2, widths = c(1, 3)),
                  all_temp, all_DO, 
                  nrow = 2, ncol= 2, 
                  align = 'hv', heights = c(1, 1.3),
                  legend = 'none', labels = c('a', '', 'b', 'c')) |> 
  ggsave(filename = 'Plots/Figure2.png', height = 20, width = 17, units = 'cm')

```

## Figure 3
```{r skill-bias-sd}
skill <- 
  temperature_skill |> 
  filter(model_id %in% c(top_mods$model_id) & model_id != 'persistenceRW', 
         horizon > 0, 
         horizon != 15,
         horizon <=30) |> 
  group_by(model_id, horizon) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  left_join(select(model_meta, model_id, manuscript_name)) |> 
  mutate(manuscript_name = factor(manuscript_name, levels = levels(model_id_colours$manuscript_name))) |> 
  ggplot(aes(x=horizon, 
             y = mean_crps, colour = manuscript_name)) +
  geom_hline(yintercept = 0, colour = 'grey40' ) + 
  geom_line(linewidth = 0.8)  +  
  labs(y='Mean relative skill (°C)', x = 'Horizon (days)') +
  scale_colour_manual(name = 'Model',values = model_id_colours$value) +
  theme_bw()



sd <- temperature_scores |> 
  mutate(horizon = as_date(datetime) - as_date(reference_datetime)) |> 
  filter(model_id %in% top_mods$model_id & model_id != 'persistenceRW',  
         horizon > 0, 
         horizon != 15,
         horizon <=30) |>
  group_by(model_id, horizon) |> 
  summarise(mean_sd = mean(sd, na.rm = T)) |> 
  left_join(select(model_meta, model_id, manuscript_name)) |> 
  mutate(manuscript_name = factor(manuscript_name, levels = levels(model_id_colours$manuscript_name))) |> 
  ggplot(aes(x=horizon, 
             y = mean_sd, colour = manuscript_name)) +
  geom_line(linewidth = 0.8)+
  labs(y='Mean standard deviation (°C)', x = 'Horizon (days)') +
  scale_colour_manual(name = 'Model',values = model_id_colours$value) +
  theme_bw()

bias <- temperature_scores |> 
  mutate(horizon = as_date(datetime) - as_date(reference_datetime),
         abs_bias = abs(mean - observation)) |> 
  filter(model_id %in% top_mods$model_id & model_id != 'persistenceRW', 
         horizon > 0, 
         horizon != 15,
         horizon <= 30) |>
  group_by(model_id, horizon) |> 
  summarise(mean_abs_bias = mean(abs_bias, na.rm = T)) |> 
  left_join(select(model_meta, model_id, manuscript_name)) |> 
  mutate(manuscript_name = factor(manuscript_name, levels = levels(model_id_colours$manuscript_name))) |> 
  ggplot(aes(x=horizon, 
             y = mean_abs_bias, colour = manuscript_name)) +
  geom_line(linewidth = 0.8)+
  labs(y='Mean absolute bias (°C)', x = 'Horizon (days)') +
  scale_colour_manual(name = 'Model',values = model_id_colours$value) +
  theme_bw() +
  coord_cartesian(ylim = c(0, 2))

ggpubr::ggarrange(skill, 
                  ggarrange(as_ggplot(get_legend(bias)), NULL, widths = c(0.5, 1.5)),  
                  sd, 
                  bias, 
                  legend = F, align = 'hv', 
                  labels = c('a','', 'b', 'c')) |> 
  ggsave(filename = 'Plots/Figure3.png', height = 17, width = 16, units = 'cm')
```

## Figure 4

```{r reliability}
source('./R/reliability_plot.R')

good_80 <- 
  plot_reliability(scores = temperature_scores,
                   models = top_mods, # model_ids and manuscript names
                   CI = 80, 
                   order = levels(model_id_colours$manuscript_name)) +
  scale_colour_manual(name = 'Top model',values = model_id_colours$value) +
  scale_linetype_manual(name = 'Top model',values = model_id_colours$linetype) +
  theme_bw() +
  scale_y_continuous(limits = c(54, 100)) +
  labs(title = 'Top performing models') +
  theme(title = element_text(size = 14))

good_95 <- plot_reliability(scores = temperature_scores,
                            models = top_mods, 
                            CI = 95, 
                            order = levels(model_id_colours$manuscript_name)) +
  scale_colour_manual(name = 'Top model',values = model_id_colours$value) +
  scale_linetype_manual(name = 'Top model',values = model_id_colours$linetype) +
  theme_bw() +
  scale_y_continuous(limits = c(54, 100))

# get the list of bad models
bad_mods <- model_meta |> 
  filter(!model_id %in% top_mods$model_id) |> 
  select(model_id, manuscript_name)

bad_80 <- 
  plot_reliability(scores = temperature_scores,
                   models = bad_mods, 
                   CI = 80, 
                   order = bad_mods$manuscript_name,
                   alpha  = 0.6) +
  theme_bw()  +
  scale_colour_manual(name = '', values = unname(pals::cols25(n= 20)))+ 
  scale_linetype_manual(name = '', values = rep('solid', 20)) +
  theme(legend.position = 'none') +
  labs(title = 'All other submitted models') +
  theme(title = element_text(size = 14))

bad_95 <- plot_reliability(scores = temperature_scores,
                           models = bad_mods, 
                           CI = 95, 
                           order = bad_mods$manuscript_name,
                           alpha  =0.6) +
  theme_bw() +
  scale_y_continuous(limits = c(0, 100))   +
  scale_colour_manual(name = '', values = unname(pals::cols25(n= 20))) + 
  scale_linetype_manual(name = '', values = rep('solid', 20)) 

ggarrange(NULL, ggarrange(get_legend(good_80), NULL, nrow = 2),
          ggarrange(good_80, good_95, bad_80, bad_95, align = 'hv', legend= 'none', labels = 'auto', hjust = -4, vjust = 3), 
          ncol = 3, 
          widths = c(0.1,1,5)) |> 
  ggsave(filename = 'Plots/Figure4.png', height = 17.6, width = 23, units = 'cm')
```

## Figure 5
```{r model_type-site}
n_model_type <- temperature_skill |> 
  distinct(model_id) |> 
  left_join(model_meta) |>
  group_by(model_type) |> 
  summarise(n = n())  |> 
  mutate(site_id = 'TOOK', mean_skill = -3.25) |> 
  filter(model_type != 'null')


# top 10 average models
top_mods <- temperature_skill |> 
  group_by(model_id) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  ungroup() |> 
  filter(mean_crps < 0) |> 
  distinct(model_id)


A <- temperature_skill |> 
  left_join(model_meta, by = 'model_id') |>
  filter(model_type != 'null') |> 
  group_by(model_type, model_id, site_id) |> 
  summarise(mean_skill = mean(skill_crps, na.rm = T)) |>  
  ggplot(aes(x = mean_skill, 
             y = site_id, 
             colour = model_type)) +
  geom_vline(xintercept = 0, linetype = 'solid') +
  geom_text(data = n_model_type, aes(label = paste0('n = ', n)))+ 
  geom_boxplot() +
  facet_wrap(~model_type, scales = 'free_y',nrow = 2) +
  labs(y='Site', x = 'Mean relative skill (°C)') +
  scale_colour_manual(values = cols_modeltype, name = 'Model class') +
  theme_bw()  +
  theme(legend.position = 'bottom')


lake_order <- temperature_skill |> 
  filter(model_id %in% top_mods$model_id) |> 
  group_by(site_id, horizon) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) %>% 
  filter(horizon == 30) %>% 
  arrange(desc(mean_crps)) %>% 
  pull(site_id)

B <- temperature_skill |> 
  filter(model_id %in% top_mods$model_id) |> 
  group_by(site_id, horizon) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  mutate(site_id = factor(site_id, levels = lake_order)) |> 
  ggplot(aes(x=horizon, 
             y = mean_crps, colour = site_id)) +
  geom_hline(yintercept = 0, colour = 'grey40') + 
  geom_line(linewidth = 0.8)  +  
  labs(y='Mean relative skill (°C)', x = 'Horizon (days)') +
  scale_colour_brewer(palette = 'Dark2', name = 'Site')+
  theme_bw()

cowplot::plot_grid(A, B, nrow = 2, rel_heights = c(1.5, 1), align = 'v', axis = 'tlbr', labels = 'auto') |> 
  ggsave(filename = './Plots/Figure5.png', width = 19, height = 16, units = 'cm')
```

## Figure 6

```{r target-plot}
targets <- readr::read_csv("targets/targets_2016-2023.csv") |> 
  na.omit() |> 
  filter(year(datetime) <= 2023)

layout_design <- "
  A#
  BC
  DE
  FG
"

# is 2023 a stand out year?
targets_2023 <- targets |> 
  filter(variable == 'temperature',
         site_id %in% lake_sites, 
         year(datetime) == 2023) |> 
  mutate(month = as.factor(month(datetime))) |> 
  group_by(month, site_id) |> 
  summarise(mean_obs = mean(observation, na.rm = T),
            n = n()) |> 
  mutate(mean_obs = ifelse(n < 18, NA, mean_obs))


obs_diff <-  
  targets |> 
  filter(variable == 'temperature',
         site_id %in% lake_sites) |> 
  mutate(month = month(datetime),
         period = ifelse(year(datetime) == 2023, 'focal', 'historic'),
         site_id = factor(site_id, levels = lake_sites)) |> 
  group_by(month, site_id, period) |> 
  summarise(median_obs = median(observation, na.rm = T),
            n = n()) |> 
  mutate(median_obs = ifelse(n < 18, NA, median_obs)) |> 
  pivot_wider(names_from = period, values_from = median_obs, id_cols = c(month, site_id)) |> 
  mutate(delta = focal - historic,
         month = as_date(paste('2023', month, '01', sep = '-'))) |> 
  ggplot()  +
  geom_hline(yintercept = 0) +
  theme_bw() +
  annotate("rect", 
           xmax = rep(as_date('2024-01-01'),8), 
           xmin = rep(as_date('2022-01-01'), 8),
           ymin = c(-Inf, -Inf, -Inf, -Inf,Inf,Inf,Inf,Inf), 
           ymax = c(-4,-3,-2,-1,1,2,3,4), 
           fill = 'grey', alpha = 0.15) +
  geom_line(aes(x=month, y=delta, colour = site_id)) +
  geom_point(aes(x=month, y=delta, colour = site_id)) +
  scale_x_date(date_labels = "%b", breaks = '1 month') +
  labs(y = 'Difference in median monthly water temperature (°C)', 
       x = 'Month') +
  coord_cartesian(xlim = c(as_date('2023-01-01'), 
                           as_date('2023-12-01')),
                  ylim = c(-2, 5.2),
                  expand = T) +
  theme(panel.grid.minor.x = element_blank()) +
  scale_colour_brewer(palette = 'Dark2', name = 'Site')


ggsave(obs_diff, filename = 'Plots/Figure6.png', width = 13, height=10, units = 'cm')

```
