---
title: "Supplementary Figures"
output: html_document
date: "2024-02-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(arrow)
library(lubridate)
library(tidytext)
library(ggpattern)
library(ggpubr)
library(ggh4x)
```

## Read in the data and model metadata
```{r read-in-data}
targets <- readr::read_csv("targets/targets_2016-2023.csv") |> 
  na.omit() 

lake_sites <- c('TOOK', 'PRLA','PRPO', 'CRAM', 'LIRO','BARC', 'SUGG')
cols_modeltype <- c('empirical' = "#482576FF",
                    'MME' =  "#35608DFF",
                    'process' = "#21908CFF",
                    'ML' = '#BBDF27FF',
                    'null' = '#A9A9A9')
# read in the metadata 
model_meta <- read_csv("https://zenodo.org/records/11087208/files/Model_descriptions.csv?download=1", na = 'character')

# Open dataset-------------
# start with lake temperatures
temperature_scores <- arrow::open_dataset("./scores") |> 
  filter(site_id %in% lake_sites,
         model_id %in% model_meta$model_id,
         variable == 'temperature') |>
  collect()


oxygen_scores <- arrow::open_dataset("./scores") |> 
  filter(site_id %in% lake_sites,
         model_id %in% model_meta$model_id,
         variable == 'oxygen') |>
  collect()


# Calculate skill scores ------------
temperature_climatology <- arrow::open_dataset("./scores") |>
  filter(model_id == 'climatology', 
         site_id %in% lake_sites,
         variable == 'temperature') |>
  collect() |> 
  select(reference_datetime, datetime, crps, logs, site_id, model_id) |> 
  arrange(reference_datetime, datetime, site_id) |> 
  pivot_wider(values_from = c(crps, logs),
              names_from = model_id)

temperature_skill <- temperature_scores |>
  filter(model_id != 'climatology') |> 
  select(reference_datetime, datetime, crps, logs, site_id, model_id) |> 
  full_join(temperature_climatology) |> 
  
  # calcaulte the skill relative to climatology (- is bad, + is good)
  mutate(skill_crps = crps - crps_climatology,
         skill_logs = logs - logs_climatology,
         horizon = as.numeric(as_date(datetime) - as_date(reference_datetime))) |> 
  # consistent forecast period
  filter(horizon <= 30,
         horizon >= 1, 
         horizon != 15) |> 
  arrange(reference_datetime, site_id, datetime, model_id)


# read in persistence scores ------------
# temp
temperature_persistence <- arrow::open_dataset("./scores") |>
  filter(model_id == 'persistenceRW', 
         variable == 'temperature') |>
  collect() |> 
  select(reference_datetime, datetime, crps, logs, site_id, model_id) |> 
  arrange(reference_datetime, datetime, site_id) |> 
  pivot_wider(values_from = c(crps, logs),
              names_from = model_id)

# DO
oxygen_persistence <- arrow::open_dataset("./scores") |>
  filter(model_id == 'persistenceRW', 
         variable == 'oxygen') |>
  collect() |> 
  select(reference_datetime, datetime, crps, logs, site_id, model_id) |> 
  arrange(reference_datetime, datetime, site_id) |> 
  pivot_wider(values_from = c(crps, logs),
              names_from = model_id)

#-------------------------#

# Calculate relative skill with persistence ------
temperature_skill_RW <- temperature_scores |>
  filter(model_id != 'persistenceRW') |> 
  select(reference_datetime, datetime, crps, logs, site_id, model_id) |> 
  full_join(temperature_persistence) |> 
  
  # calcaulte the skill relative to climatology (- is bad, + is good)
  mutate(skill_crps = crps - crps_persistenceRW,
         skill_logs = logs - logs_persistenceRW,
         horizon = as.numeric(as_date(datetime) - as_date(reference_datetime))) |> 
  # consistent forecast period
  filter(horizon <= 30,
         horizon >= 1, 
         horizon != 15) |> 
  arrange(reference_datetime, site_id, datetime, model_id) 


oxygen_skill_RW <- oxygen_scores |>
  filter(model_id != 'persistenceRW') |> 
  select(reference_datetime, datetime, crps, logs, site_id, model_id) |> 
  full_join(oxygen_persistence) |> 
  
  # calcaulte the skill relative to persistenceRW (- is bad, + is good)
  mutate(skill_crps = crps - crps_persistenceRW,
         skill_logs = logs - logs_persistenceRW,
         horizon = as.numeric(as_date(datetime) - as_date(reference_datetime))) |> 
  # consistent forecast period
  filter(horizon <= 30,
         horizon >= 1, 
         horizon != 15) |> 
  arrange(reference_datetime, site_id, datetime, model_id) 


baselines <- model_meta |> 
  filter(model_id %in% c('persistenceRW', 'climatology'))

source('R/get_colours.R')

if (!dir.exists('Plots')) {
  dir.create('Plots')
}
```
## Figure s1 - targets timeseries

```{r}
targets_ts <- targets |> 
  filter(year(datetime) < 2023,
         site_id %in% lake_sites) |> 
  ggplot(aes(x=datetime, y=variable, colour = variable)) +
  geom_point(show.legend = F) +
  facet_wrap(~site_id, ncol = 3) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  scale_colour_viridis_d(option = 'A', begin=0.2, end=0.9)

ggsave(plot = targets_ts, 'Plots/FigureS1.png', width = 20, height = 15, units = 'cm')
```


## Figure S2 - all models, skill over horizon

```{r}
top_mods <- temperature_skill |> 
  group_by(model_id) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  ungroup() |> 
  filter(mean_crps < 0) |> 
  distinct(model_id)

horizon_skill <- 
  temperature_skill |> 
  filter(!(model_id %in% c(top_mods$model_id)), 
         horizon > 0, 
         horizon != 15,
         horizon <=30) |> 
  group_by(model_id, horizon) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  left_join(select(model_meta, model_id, manuscript_name)) |> 
  # mutate(manuscript_name = factor(manuscript_name, levels = levels(model_id_colours$manuscript_name))) |> 
  ggplot(aes(x=horizon, 
             y = mean_crps, colour = manuscript_name, linetype = manuscript_name)) +
  geom_hline(yintercept = 0, colour = 'grey40' ) + 
  geom_line(show.legend = F)  +  
  labs(y='Mean relative skill (°C)', x = 'Horizon (days)') +
  theme_bw()

ggsave(plot = horizon_skill, 'Plots/FigureS2.png', width = 10, height = 10, units = 'cm')
```

## Figure S3 - performance of null models

```{r}
baseline_forecasts <- arrow::open_dataset("scores") |>
  filter(site_id %in% lake_sites,
         model_id %in% c('persistenceRW', 'climatology')) |>
  collect()


baseline1<-baseline_forecasts |> 
  mutate(horizon = as.numeric(as_date(datetime) - as_date(reference_datetime)),
         site_id = factor(site_id, levels = lake_sites)) |> 
  group_by(site_id, model_id, horizon) |> 
  summarise(crps_median = median(crps, na.rm = T), .groups = 'drop') |> 
  ggplot(aes(x=horizon, y=crps_median, colour = site_id)) +
  geom_line() +
  facet_wrap(~model_id) +
  scale_colour_brewer(palette = 'Dark2', name = 'Site') +
  labs(y='Median CRPS (°C)', x = 'Horizon (days)') +
  theme_bw() 

baseline2<-baseline_forecasts |> 
  mutate(horizon = as.numeric(as_date(datetime) - as_date(reference_datetime))) |> 
  group_by(site_id, model_id, reference_datetime) |> 
  summarise(crps_median = median(crps, na.rm = T), .groups = 'drop') |> 
  ggplot(aes(x = as_date(reference_datetime), y=crps_median, colour = site_id)) +
  geom_line() +
  facet_wrap(~model_id, scale = 'free_y') +
  scale_colour_brewer(palette = 'Dark2', name = 'Site') +
  labs(y='Median CRPS (°C)', x = 'Forecast date') +
  theme_bw()


ggarrange(baseline1, baseline2, nrow = 2) |> 
  ggsave(filename = './Plots/FigureS3.png', width = 19, height = 16, units = 'cm')
```

## Figure S4

Plotting only dates where all sites are evaluated shows the same pattern as when all dates are considered. 
```{r overlapping-periods}
n_model_type <- temperature_skill |> 
  distinct(model_id) |> 
  left_join(model_meta) |>
  group_by(model_type) |> 
  summarise(n = n())  |> 
  mutate(site_id = 'TOOK', mean_skill = 3.25) |> 
  filter(model_type != 'null')


# top 10 average models
top_mods <- temperature_skill |> 
  group_by(model_id) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  ungroup() |> 
  filter(mean_crps < 0) |> 
  distinct(model_id)

# what duration have the same dates, including TOOK
date_same_A <-  temperature_skill |> 
  na.omit() |> 
  group_by(site_id) |> 
  summarise(first_date = min(datetime), 
            last_date = max(datetime)) |> 
  summarise(first_date = max(first_date),
            last_date = min(last_date))

# what duration have the same dates, including TOOK
date_same_B <- temperature_skill |> 
  filter(site_id != 'TOOK') |> 
  na.omit()  |> 
  group_by(site_id) |> 
  summarise(first_date = min(datetime), 
            last_date = max(datetime)) |> 
  summarise(first_date = max(first_date),
            last_date = min(last_date))

A <- temperature_skill |>
  left_join(model_meta, by = 'model_id') |>
  filter(model_type != 'null',
         between(datetime, date_same_B$first_date, date_same_B$last_date)) |>
  group_by(model_type, model_id, site_id) |>
  summarise(mean_skill = mean(skill_crps, na.rm = T)) |>
  ggplot(aes(x = mean_skill,
             y = site_id,
             colour = model_type)) +
  geom_vline(xintercept = 0, linetype = 'solid') +
  geom_text(data = n_model_type, aes(label = paste0('n = ', n)))+
  geom_boxplot() +
  facet_wrap(~model_type, scales = 'free_y',nrow = 2) +
  labs(y='Site', x = 'mean relative skill (°C)') +
  scale_colour_manual(values = cols_modeltype, name = 'Model class') +
  theme_bw()


lake_order <- temperature_skill |> 
  filter(model_id %in% top_mods$model_id) |> 
  group_by(site_id, horizon) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) %>% 
  filter(horizon == 30) %>% 
  arrange(desc(mean_crps)) %>% 
  pull(site_id)


B <- temperature_skill |> 
  filter(model_id %in% top_mods$model_id, 
         between(datetime, date_same_B$first_date, date_same_B$last_date)) |> 
  group_by(site_id, horizon) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  mutate(site_id = factor(site_id, levels = lake_order)) |> 
  ggplot(aes(x=horizon, 
             y = mean_crps, colour = site_id)) +
  geom_hline(yintercept = 0, colour = 'grey40') + 
  geom_line()  +  
  labs(y='mean relative skill (°C)', x = 'Horizon (days)') +
  scale_colour_brewer(palette = 'Dark2', name = 'Site') +
  theme_bw()

cowplot::plot_grid(A, B, nrow = 2, rel_heights = c(1.5, 1), align = 'v', axis = 'lr', labels = 'auto') |> 
  ggsave(filename = './Plots/FigureS4.png', width = 19, height = 16, units = 'cm')
```
```{r}
skill_summary_RW <- temperature_skill_RW |>
  group_by(model_id) |>
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |>
  ungroup() |>
  filter(mean_crps < 0) |>
  left_join(model_meta) |>
  mutate(manuscript_name = fct_reorder(manuscript_name, mean_crps),
         uses_NOAA = ifelse(uses_NOAA == 1, 'yes', 'no'),
         uses_AT = str_detect(NOAA_var, 'air_temperature')) |>
  ggplot(aes(x=mean_crps, y = manuscript_name, fill = model_type)) +    # Different pattern for each group
  geom_bar_pattern(aes(pattern = as.factor(uses_AT)),
                   stat = "identity",
                   alpha = 0.8,
                   pattern_fill = "black",
                   pattern_colour = "black",
                   pattern_spacing = 0.04,
                   pattern_alpha = 1,
                   colour = 'black') +
  scale_y_reordered() +
  labs(y='Model', x = 'Mean relative skill (°C)') +
  geom_vline(xintercept = 0) +
  scale_fill_manual(values = cols_modeltype) +
  scale_pattern_manual(values=c('none', 'stripe')) +
  scale_pattern_type_manual(values=c(NA, NA)) +
  theme_bw(base_size = 10) +
  guides(pattern = guide_legend(override.aes = list(fill = "white", pattern_spacing = 0.02),
                                title = 'Uses air temperature\nas a covariate?'),
         fill = guide_legend(override.aes = list(pattern = "none"), title = 'Model class')) +
    theme(legend.box = 'horizontal')


skill_summary_RW_nolegend <- skill_summary_RW +
  theme(legend.position = 'none')


skill_horizon_RW <- temperature_skill_RW |> 
  filter(model_id %in% c(top_mods$model_id) & model_id != 'climatology', 
         horizon > 0, 
         horizon != 15,
         horizon <=30) |> 
  group_by(model_id, horizon) |> 
  summarise(mean_crps = mean(skill_crps, na.rm = T)) |> 
  left_join(select(model_meta, model_id, manuscript_name)) |> 
  mutate(manuscript_name = factor(manuscript_name, levels = levels(model_id_colours$manuscript_name))) |> 
  ggplot(aes(x=horizon, 
             y = mean_crps, colour = manuscript_name)) +
  geom_hline(yintercept = 0, colour = 'grey40' ) + 
  geom_line(linewidth = 0.8)  +  
  labs(y='Mean relative skill (°C)', x = 'Horizon (days)') +
  scale_colour_manual(name = 'Model',values = model_id_colours$value) +
  theme_bw()

ggpubr::ggarrange(ggarrange(NULL, as_ggplot(get_legend(skill_summary_RW)), NULL, NULL, widths =  c(0.2, 0.9,0.2, 1.1), nrow = 1),
                  ggarrange(skill_summary_RW_nolegend,  NULL, skill_horizon_RW, align = 'h', widths =  c(0.9,0.05, 1.1), nrow = 1), 
                  heights = c(0.5, 1),nrow = 2) |> 
  ggsave(filename = 'Plots/FigureSnew.png', height = 17, width = 18, units = 'cm')
```
```{r}
null_scores <- temperature_scores |> mutate(horizon = as.numeric(as_date(datetime) - as_date(reference_datetime))) %>% 
  filter(model_id %in% baselines$model_id, 
         horizon > 0, 
         horizon != 15,
         horizon <=30) |> 
  group_by(model_id, horizon) |> 
  summarise(mean_crps = mean(crps, na.rm = T)) %>% 
  mutate(model_id = factor(model_id, levels = c('climatology', 'persistenceRW'), labels = c("day-of-year", "persistence"))) %>% 
  ggplot(aes(x=horizon,y = mean_crps, colour = model_id)) + 
  geom_line() + 
  scale_x_continuous(breaks = seq(2,30, 2)) + 
  theme_bw() + 
  labs(x= 'Horizon (days)', y = 'Mean CRPS (°C)') + 
  scale_colour_viridis_d(name = 'Null Model', begin = 0.2, end=0.9) +
  theme(panel.grid.minor = element_blank())

ggsave(null_scores, filename = 'Plots/Figure_Snew2.png', height = 10, width = 15, units = 'cm')
```

```{r}

temp_skill_RW_summary <- temperature_skill_RW |> 
  filter(model_id %in% c(top_mods$model_id) & model_id != 'climatology', 
         horizon > 0, 
         horizon != 15,
         horizon <=30) |> 
  group_by(model_id, horizon) |> 
  summarise(mean_crpsRW = mean(skill_crps, na.rm = T)) |> 
  left_join(select(model_meta, model_id, manuscript_name)) |> 
  mutate(manuscript_name = factor(manuscript_name, levels = levels(model_id_colours$manuscript_name)))

temp_skill_clim_summary <- temperature_skill |> 
  filter(model_id %in% c(top_mods$model_id) & model_id != 'persistence', 
         horizon > 0, 
         horizon != 15,
         horizon <=30) |> 
  group_by(model_id, horizon) |> 
  summarise(mean_crpsDOY = mean(skill_crps, na.rm = T)) |> 
  left_join(select(model_meta, model_id, manuscript_name)) |> 
  mutate(manuscript_name = factor(manuscript_name, levels = levels(model_id_colours$manuscript_name)))


null_model_beats <- full_join(temp_skill_clim_summary, temp_skill_RW_summary, 
          by = join_by(model_id, horizon, manuscript_name)) %>% 
  mutate(beats = ifelse(mean_crpsDOY < 0 & mean_crpsRW < 0, 'both',
                        ifelse(mean_crpsDOY > 0 & mean_crpsRW < 0, 'RW',
                               ifelse(mean_crpsDOY < 0 & mean_crpsRW > 0, 'DOY', 'none')))) %>% 
  mutate(beats = factor(beats, levels = c("none", "RW", "DOY", "both"), labels = c("Neither", "Persistence", "Day-of-year", "Both"))) %>% 
  na.omit() %>% 
  ggplot(aes(x=horizon, y=manuscript_name, shape = beats, colour = beats)) + 
  geom_point(size = 5) +
  scale_shape_manual(values = c(0, 1, 4, 13), name = 'Null model that is out-performed') +
  scale_colour_manual(values = c("grey90", "#455BCDFF", "#E1DD37FF", "#46F884FF"), name = 'Null model that is out-performed') +
  scale_y_discrete(name = 'Model') +
  scale_x_continuous(name = 'Horizon (days)', breaks = c(1,10, 20, 30), expand = c(0.02,0)) +
  geom_hline(yintercept = seq(.5, 9.5, 1), linewidth = .2) +
  theme(legend.position = "bottom", 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.text = element_text(size = 8),
        legend.title = element_text(size = 8),
        axis.ticks.y = element_blank())

ggsave(null_model_beats, filename = 'Plots/Figure_Snew3.png', height = 10, width = 18, units = 'cm')

```


